version: 2
# .goreleaser.yml
# Build customization
builds:
  - id: "gopretty"
    binary: gopretty
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
brews:
  - name: gopretty
    directory: Formula
    repository:
      owner: fsuhrau
      name: homebrew-tap
      branch: master
    caveats: "xcodebuild -project 'testproject.xcodeproj' -configuration Release -target \"test\" | gopretty"
    homepage: "https://github.com/fsuhrau/gopretty"
    description: "Go Pretty a small beautifier for XCode builds similar to xcpretty"
 